'use client';

export default function TuningSyntheticBanner() {
  return (
    <div className="w-full bg-ourox-obsidianMid border-b border-ourox-orange/20 px-6 py-2.5 flex items-center gap-3">
      <span className="inline-flex items-center gap-1.5 bg-ourox-orange/10 text-ourox-orange text-xs font-semibold px-2.5 py-1 rounded-full border border-ourox-orange/30 tracking-wide uppercase">
        SYNTHETIC DATA
      </span>
      <span className="text-ourox-ink/50 text-xs">
        All events are generated by Mockingbird. No real customer data. Tuning changes are sandbox-only — no live production config is modified.
      </span>
    </div>
  );
}
